// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/Achievement": {
            "get": {
                "tags": [
                    "公共方法"
                ],
                "summary": "获取成就列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "pageSize",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "keyWord",
                        "name": "keyWord",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":\"200\",\"msg\":\"\",\"data\",\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/BodyJSONTest": {
            "post": {
                "tags": [
                    "测试方法"
                ],
                "summary": "BodyJSONTest",
                "parameters": [
                    {
                        "description": "上传的JSON",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":\"200\",\"msg\":\"\",\"data\",\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/Class": {
            "get": {
                "tags": [
                    "公共方法"
                ],
                "summary": "获取班级列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "pageSize",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "keyWord",
                        "name": "keyWord",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":\"200\",\"msg\":\"\",\"data\",\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/Knowledge": {
            "get": {
                "tags": [
                    "公共方法"
                ],
                "summary": "获取知识点列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "pageSize",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "keyWord",
                        "name": "keyWord",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":\"200\",\"msg\":\"\",\"data\",\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/Login": {
            "post": {
                "tags": [
                    "公共方法"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "登陆信息",
                        "name": "json",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/service.loginAccept"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":\"200\",\"msg\":\"\",\"data\",\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/PostArrayTest": {
            "post": {
                "tags": [
                    "测试方法"
                ],
                "summary": "PostArrayTest",
                "parameters": [
                    {
                        "type": "array",
                        "description": "array",
                        "name": "param",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":\"200\",\"msg\":\"\",\"data\",\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/Register": {
            "post": {
                "tags": [
                    "公共方法"
                ],
                "summary": "Register",
                "parameters": [
                    {
                        "description": "此处email由VerifyEmailCode得来;status以什么身份注册1为学生2为老师",
                        "name": "json",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.registerAccept"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":\"200\",\"msg\":\"\",\"data\",\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/SendCode": {
            "post": {
                "tags": [
                    "公共方法"
                ],
                "summary": "SendCode",
                "parameters": [
                    {
                        "description": "email",
                        "name": "json",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/service.sendCodeAccept"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":\"200\",\"msg\":\"\",\"data\",\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/VerifyEmailCode": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "公共方法"
                ],
                "summary": "验证码是否真确",
                "parameters": [
                    {
                        "description": "此处email由SendCode得来",
                        "name": "code",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.verifyEmailCodeAccept"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/student/Class": {
            "put": {
                "tags": [
                    "学生方法"
                ],
                "summary": "加入班级",
                "parameters": [
                    {
                        "type": "string",
                        "description": "joinCode",
                        "name": "joinCode",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":\"200\",\"msg\":\"\",\"data\",\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/teacher/Achievement": {
            "post": {
                "tags": [
                    "老师方法"
                ],
                "summary": "添加知识点成就",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "knowledgeIdentity",
                        "name": "knowledgeIdentity",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":\"200\",\"msg\":\"\",\"data\",\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/teacher/Class": {
            "put": {
                "tags": [
                    "老师方法"
                ],
                "summary": "修改班级",
                "parameters": [
                    {
                        "description": "上传的JSON",
                        "name": "param",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.updateClassAccept"
                        }
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":\"200\",\"msg\":\"\",\"data\",\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "老师方法"
                ],
                "summary": "创建班级",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":\"200\",\"msg\":\"\",\"data\",\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/teacher/ClassStudents": {
            "get": {
                "tags": [
                    "老师方法"
                ],
                "summary": "获取班级学生列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "classIdentity",
                        "name": "classIdentity",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "pageSize",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "keyWord",
                        "name": "keyWord",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":\"200\",\"msg\":\"\",\"data\",\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/teacher/Knowledge": {
            "put": {
                "tags": [
                    "老师方法"
                ],
                "summary": "修改知识点",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "identity",
                        "name": "identity",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":\"200\",\"msg\":\"\",\"data\",\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "老师方法"
                ],
                "summary": "添加知识点",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":\"200\",\"msg\":\"\",\"data\",\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "老师方法"
                ],
                "summary": "删除知识点",
                "parameters": [
                    {
                        "type": "string",
                        "description": "identity",
                        "name": "identity",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":\"200\",\"msg\":\"\",\"data\",\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/teacher/ProblemCategory": {
            "get": {
                "tags": [
                    "老师方法"
                ],
                "summary": "获取题目类型列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "pageSize",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "keyWord",
                        "name": "keyWord",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":\"200\",\"msg\":\"\",\"data\",\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "老师方法"
                ],
                "summary": "添加题目类型",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":\"200\",\"msg\":\"\",\"data\",\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "老师方法"
                ],
                "summary": "删除题目类型",
                "parameters": [
                    {
                        "type": "string",
                        "description": "identity",
                        "name": "identity",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\":\"200\",\"msg\":\"\",\"data\",\"\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "service.loginAccept": {
            "type": "object",
            "required": [
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "service.registerAccept": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "service.sendCodeAccept": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "service.updateClassAccept": {
            "type": "object",
            "required": [
                "class_identity",
                "is_change_code"
            ],
            "properties": {
                "class_identity": {
                    "type": "string"
                },
                "class_name": {
                    "type": "string"
                },
                "is_change_code": {
                    "type": "boolean"
                },
                "student_identities": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "service.verifyEmailCodeAccept": {
            "type": "object",
            "required": [
                "code",
                "email"
            ],
            "properties": {
                "code": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
