definitions:
  service.addAchievementAccept:
    properties:
      knowledge_identity:
        type: string
      name:
        type: string
    required:
    - knowledge_identity
    - name
    type: object
  service.addKnowledgeAccept:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  service.addProblemAccept:
    properties:
      answer:
        type: string
      categoryIdentity:
        type: string
      content:
        type: string
      knowledgeIdentities:
        items:
          type: string
        type: array
      name:
        type: string
      score:
        type: integer
    required:
    - answer
    - categoryIdentity
    - content
    - knowledgeIdentities
    - name
    - score
    type: object
  service.addProblemCategoryAccept:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  service.createClassAccept:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  service.deleteKnowledgeAccept:
    properties:
      identity:
        type: string
    required:
    - identity
    type: object
  service.deleteProblemCategoryAccept:
    properties:
      identity:
        type: string
    required:
    - identity
    type: object
  service.joinClassAccept:
    properties:
      joinCode:
        type: string
    required:
    - joinCode
    type: object
  service.loginAccept:
    properties:
      name:
        type: string
      password:
        type: string
    required:
    - name
    - password
    type: object
  service.registerAccept:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      phone:
        type: string
      status:
        type: string
    required:
    - email
    - name
    - password
    type: object
  service.sendCodeAccept:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  service.updateClassAccept:
    properties:
      class_identity:
        type: string
      class_name:
        type: string
      is_change_code:
        type: boolean
      student_identities:
        items:
          type: string
        type: array
    required:
    - class_identity
    - is_change_code
    type: object
  service.updateKnowledgeAccept:
    properties:
      identity:
        type: string
      name:
        type: string
    required:
    - identity
    - name
    type: object
  service.updateProblemAccept:
    properties:
      answer:
        type: string
      categoryIdentity:
        type: string
      content:
        type: string
      identity:
        type: string
      knowledgeIdentities:
        items:
          type: string
        type: array
      name:
        type: string
      score:
        type: integer
    required:
    - identity
    type: object
  service.verifyEmailCodeAccept:
    properties:
      code:
        type: string
      email:
        type: string
    required:
    - code
    - email
    type: object
info:
  contact: {}
paths:
  /Achievement:
    get:
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: page
        in: query
        name: page
        type: string
      - description: pageSize
        in: query
        name: pageSize
        type: string
      - description: keyWord
        in: query
        name: keyWord
        type: string
      responses:
        "200":
          description: code":"200","msg":"","data",""}
          schema:
            type: string
      summary: 获取成就列表
      tags:
      - 公共方法
  /BodyJSONTest:
    post:
      parameters:
      - description: 上传的JSON
        in: body
        name: param
        required: true
        schema:
          type: string
      responses:
        "200":
          description: code":"200","msg":"","data",""}
          schema:
            type: string
      summary: BodyJSONTest
      tags:
      - 测试方法
  /Class:
    get:
      parameters:
      - description: page
        in: query
        name: page
        type: string
      - description: pageSize
        in: query
        name: pageSize
        type: string
      - description: keyWord
        in: query
        name: keyWord
        type: string
      - description: token
        in: header
        name: token
        required: true
        type: string
      responses:
        "200":
          description: code":"200","msg":"","data",""}
          schema:
            type: string
      summary: 获取班级列表
      tags:
      - 公共方法
  /Knowledge:
    get:
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: page
        in: query
        name: page
        type: string
      - description: pageSize
        in: query
        name: pageSize
        type: string
      - description: keyWord
        in: query
        name: keyWord
        type: string
      responses:
        "200":
          description: code":"200","msg":"","data",""}
          schema:
            type: string
      summary: 获取知识点列表
      tags:
      - 公共方法
  /Login:
    post:
      parameters:
      - description: 登陆信息
        in: body
        name: json
        schema:
          $ref: '#/definitions/service.loginAccept'
      responses:
        "200":
          description: code":"200","msg":"","data",""}
          schema:
            type: string
      summary: 用户名登陆
      tags:
      - 公共方法
  /PostArrayTest:
    post:
      parameters:
      - description: array
        in: formData
        name: param
        required: true
        type: array
      responses:
        "200":
          description: code":"200","msg":"","data",""}
          schema:
            type: string
      summary: PostArrayTest
      tags:
      - 测试方法
  /Register:
    post:
      parameters:
      - description: status以什么身份注册1为学生2为老师
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/service.registerAccept'
      responses:
        "200":
          description: code":"200","msg":"","data",""}
          schema:
            type: string
      summary: Register
      tags:
      - 公共方法
  /SendCode:
    post:
      parameters:
      - description: email
        in: body
        name: json
        schema:
          $ref: '#/definitions/service.sendCodeAccept'
      responses:
        "200":
          description: code":"200","msg":"","data",""}
          schema:
            type: string
      summary: SendCode
      tags:
      - 公共方法
  /VerifyEmailCode:
    post:
      consumes:
      - application/json
      parameters:
      - description: 此处email由SendCode得来
        in: body
        name: code
        required: true
        schema:
          $ref: '#/definitions/service.verifyEmailCodeAccept'
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 邮箱验证码登陆
      tags:
      - 公共方法
  /student/Class:
    put:
      parameters:
      - description: json
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/service.joinClassAccept'
      - description: token
        in: header
        name: token
        required: true
        type: string
      responses:
        "200":
          description: code":"200","msg":"","data",""}
          schema:
            type: string
      summary: 加入班级
      tags:
      - 学生方法
  /teacher/Achievement:
    post:
      parameters:
      - description: json
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/service.addAchievementAccept'
      - description: token
        in: header
        name: token
        required: true
        type: string
      responses:
        "200":
          description: code":"200","msg":"","data",""}
          schema:
            type: string
      summary: 添加知识点成就
      tags:
      - 老师方法
  /teacher/Class:
    post:
      parameters:
      - description: json
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/service.createClassAccept'
      - description: token
        in: header
        name: token
        required: true
        type: string
      responses:
        "200":
          description: code":"200","msg":"","data",""}
          schema:
            type: string
      summary: 创建班级
      tags:
      - 老师方法
    put:
      parameters:
      - description: 上传的JSON
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/service.updateClassAccept'
      - description: token
        in: header
        name: token
        type: string
      responses:
        "200":
          description: code":"200","msg":"","data",""}
          schema:
            type: string
      summary: 修改班级
      tags:
      - 老师方法
  /teacher/Class/{identity}:
    get:
      parameters:
      - description: class_identity
        in: path
        name: identity
        required: true
        type: string
      - description: token
        in: header
        name: token
        type: string
      responses:
        "200":
          description: code":"200","msg":"","data",""}
          schema:
            type: string
      summary: 获取班级详情
      tags:
      - 老师方法
  /teacher/ClassStudents:
    get:
      parameters:
      - description: classIdentity
        in: query
        name: classIdentity
        required: true
        type: string
      - description: page
        in: query
        name: page
        type: string
      - description: pageSize
        in: query
        name: pageSize
        type: string
      - description: keyWord
        in: query
        name: keyWord
        type: string
      - description: token
        in: header
        name: token
        required: true
        type: string
      responses:
        "200":
          description: code":"200","msg":"","data",""}
          schema:
            type: string
      summary: 获取班级学生列表
      tags:
      - 老师方法
  /teacher/Knowledge:
    delete:
      parameters:
      - description: json
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/service.deleteKnowledgeAccept'
      - description: token
        in: header
        name: token
        required: true
        type: string
      responses:
        "200":
          description: code":"200","msg":"","data",""}
          schema:
            type: string
      summary: 删除知识点
      tags:
      - 老师方法
    post:
      parameters:
      - description: json
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/service.addKnowledgeAccept'
      - description: token
        in: header
        name: token
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 添加知识点
      tags:
      - 老师方法
    put:
      parameters:
      - description: json
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/service.updateKnowledgeAccept'
      - description: token
        in: header
        name: token
        required: true
        type: string
      responses:
        "200":
          description: code":"200","msg":"","data",""}
          schema:
            type: string
      summary: 修改知识点
      tags:
      - 老师方法
  /teacher/Problem:
    post:
      parameters:
      - description: json
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/service.addProblemAccept'
      - description: token
        in: header
        name: token
        required: true
        type: string
      responses:
        "200":
          description: code":"200","msg":"","data",""}
          schema:
            type: string
      summary: 创建题目
      tags:
      - 老师方法
    put:
      parameters:
      - description: json
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/service.updateProblemAccept'
      - description: token
        in: header
        name: token
        required: true
        type: string
      responses:
        "200":
          description: code":"200","msg":"","data",""}
          schema:
            type: string
      summary: 修改题目
      tags:
      - 老师方法
  /teacher/ProblemCategory:
    delete:
      parameters:
      - description: json
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/service.deleteProblemCategoryAccept'
      - description: token
        in: header
        name: token
        required: true
        type: string
      responses:
        "200":
          description: code":"200","msg":"","data",""}
          schema:
            type: string
      summary: 删除题目类型
      tags:
      - 老师方法
    get:
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      - description: page
        in: query
        name: page
        type: string
      - description: pageSize
        in: query
        name: pageSize
        type: string
      - description: keyWord
        in: query
        name: keyWord
        type: string
      responses:
        "200":
          description: code":"200","msg":"","data",""}
          schema:
            type: string
      summary: 获取题目类型列表
      tags:
      - 老师方法
    post:
      parameters:
      - description: json
        in: body
        name: json
        schema:
          $ref: '#/definitions/service.addProblemCategoryAccept'
      - description: token
        in: header
        name: token
        required: true
        type: string
      responses:
        "200":
          description: code":"200","msg":"","data",""}
          schema:
            type: string
      summary: 添加题目类型
      tags:
      - 老师方法
swagger: "2.0"
